---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    exclude-paths:
      - "log4j2-legacy-tests"
      - "log4j-legacy-tests"
      - "logback-legacy-tests"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: "/"
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '22:00'
    open-pull-requests-limit: 5
    labels:
      - 'changelog:dependencies'
