agents:
  provider: "gcp"
  #image: "family/ecs-logging-java-ubuntu-2204"

steps:
  - label: "Run the release"
    key: "release"
    commands: .ci/release.sh
    artifact_paths: "release.txt"

notify:
  - slack:
      channels:
        - "#apm-agent-java"
