agents:
  provider: "gcp"

steps:
  - label: "Run the snapshot"
    key: "release"
    commands: .ci/snapshot.sh
    artifact_paths:
      - "snapshot.txt"
      - "**/target/*"

notify:
  - slack:
    if: build.state == "failed"
      channels:
        - "#apm-agent-java"
