#!/usr/bin/env bash
##  This script reverts the Vault context for the release and snapshot pipelines.
##
##  NOTE: *_SECRET env variables are masked, hence if you'd like to avoid any
##        surprises please use the suffix _SECRET for those values that contain
##        any sensitive data. Buildkite can mask those values automatically

set -euo pipefail

VAULT_TOKEN=$VAULT_TOKEN_PREVIOUS
export VAULT_TOKEN
