---
# Send PRs to the subscribed ECS Agents if the spec files (JSON) are modified
name: update-specs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: elastic/apm-pipeline-library/.github/actions/updatecli@current
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          pipeline: ./.ci/update-specs.yml
